export enum FontSize {
  TextXs = "text-xs",
  TextSm = "text-sm",
  TextBase = "text-base",
  TextLg = "text-lg",
  TextXl = "text-xl",
  Text2xl = "text-2xl",
  Text3xl = "text-3xl",
  Text4xl = "text-4xl",
  Text5xl = "text-5xl",
  Text6xl = "text-6xl",
  Text7xl = "text-7xl",
  Text8xl = "text-8xl",
  Text9xl = "text-9xl",
}

export const FONT_SIZES: Record<string, FontSize> = {
  xs: FontSize.TextXs,
  sm: FontSize.TextSm,
  base: FontSize.TextBase,
  lg: FontSize.TextLg,
  xl: FontSize.TextXl,
  "2xl": FontSize.Text2xl,
  "3xl": FontSize.Text3xl,
  "4xl": FontSize.Text4xl,
  "5xl": FontSize.Text5xl,
  "6xl": FontSize.Text6xl,
  "7xl": FontSize.Text7xl,
  "8xl": FontSize.Text8xl,
  "9xl": FontSize.Text9xl,
};
